Do not check for 'foo' commits

diff --git a/pre-push b/pre-push
--- a/pre-push
+++ b/pre-push
@@ -43,16 +43,16 @@ do
 		fi
 
 		# Check for foo commit
-		commit=`git rev-list -n 1 --grep '^foo' "$range"`
-		if [ -n "$commit" ]
-		then
-			echo "ERROR: git pre-push hook found commit message starting with 'foo' in $local_ref"
-			echo "Eliminate the bad commit message by either:"
-			echo "git commit --amend -m 'New commit message'"
-			echo "or by editing the commit message while rebasing the commit."
-			echo "--------------\n"
-			exit 1
-		fi
+		# commit=`git rev-list -n 1 --grep '^foo' "$range"`
+		# if [ -n "$commit" ]
+		# then
+		# 	echo "ERROR: git pre-push hook found commit message starting with 'foo' in $local_ref"
+		# 	echo "Eliminate the bad commit message by either:"
+		# 	echo "git commit --amend -m 'New commit message'"
+		# 	echo "or by editing the commit message while rebasing the commit."
+		# 	echo "--------------\n"
+		# 	exit 1
+		# fi
 
 		# Check for . commit
 		#commit=`git rev-list -n 1 --grep '^\.' "$range"`
